const modules = [
  { id: 'A', title: 'Se repérer', description: 'Comprendre où l’on est et comment se déplacer.', missions: ['01','02','03'] },
  { id: 'B', title: 'Manipuler les fichiers', description: 'Copier, renommer et sélectionner sans se tromper.', missions: ['04','05','06'] },
  { id: 'C', title: 'Faire parler les données', description: 'Redirections, tuyaux et recherche dans le texte.', missions: ['07','08','09','10','11'] },
  { id: 'D', title: 'Aller plus loin', description: 'Droits, archives, expressions régulières et nettoyage.', missions: ['12','13','14','15'] },
  {"id":"E","title":"Fichiers et stockage","description":"Liens, droits privés, place disque et sauvegardes.","missions":["16","17","18","19","20"]},
  {"id":"F","title":"Journaux et données","description":"Extraire le signal utile des logs et des fichiers de configuration.","missions":["21","22","23","24","25"]},
  {"id":"G","title":"Processus et shell","description":"Observer les processus et maîtriser l’environnement de commande.","missions":["26","27","28","29","30"]},
  {"id":"H","title":"Automatiser en Bash","description":"Écrire des scripts réutilisables et résoudre un incident.","missions":["31","32","33","34","35"]},
  {"id":"I","title":"AlmaLinux en pratique","description":"Paquets RPM, services, journaux, réseau et SELinux.","missions":["36","37","38","39","40","41","42"]}
];

const missions = [
  {id:'01', title:'Où suis-je ?', subtitle:'Se déplacer et enregistrer un chemin', time:'5 min', tags:['pwd','cd','>'], token:'ORBITE-01', scenario:'Tu viens d’ouvrir un terminal. Avant de manipuler des fichiers, tu dois savoir dans quel dossier tu te trouves et te déplacer vers les données de l’atelier.', steps:['Place-toi dans le dossier <code>donnees</code>.','Enregistre son chemin complet dans <code>reponses/01-position.txt</code>.','Reviens à la racine de <code>atelier-linux</code> pour la suite.'], note:'Le fichier de réponse doit contenir le chemin produit par <code>pwd</code>, pas une adresse recopiée à la main.', hints:['<code>cd</code> change de dossier ; <code>pwd</code> affiche le chemin du dossier courant.','Depuis <code>donnees</code>, le dossier <code>reponses</code> se trouve un niveau plus haut : <code>../reponses</code>.'], solution:'cd donnees\npwd > ../reponses/01-position.txt\ncd ..', tip:'Le caractère <code>..</code> désigne le dossier parent. Le caractère <code>~</code> désigne ton dossier personnel.'},
  {id:'02', title:'Garder l’original', subtitle:'Copier avec un chemin relatif', time:'4 min', tags:['ls','cp','chemins'], token:'RACINE-02', scenario:'Un collègue t’a transmis une note. Tu veux en faire une copie de travail tout en conservant l’original.', steps:['Repère <code>donnees/notes/depart.txt</code> avec <code>ls</code>.','Copie-le sous le nom <code>reponses/02-copie.txt</code>.','Vérifie que les deux fichiers existent.'], hints:['<code>cp source destination</code> crée une copie.','Les deux chemins peuvent être relatifs au dossier <code>atelier-linux</code>.'], solution:'ls donnees/notes\ncp donnees/notes/depart.txt reponses/02-copie.txt\nls reponses/02-copie.txt donnees/notes/depart.txt', tip:'La plupart des commandes qui modifient les fichiers restent silencieuses quand tout va bien : vérifie avec <code>ls</code>.'},
  {id:'03', title:'Préparer un espace de travail', subtitle:'Créer un dossier et un fichier vide', time:'4 min', tags:['mkdir','touch','ls'], token:'DOSSIER-03', scenario:'Le dossier <code>travail</code> contiendra tes productions. Il lui manque un espace pour les rapports.', steps:['Crée le dossier <code>travail/rapports</code>.','Crée dedans un fichier vide nommé <code>bilan.txt</code>.','Affiche le contenu du dossier pour confirmer.'], hints:['<code>mkdir</code> crée un dossier.','<code>touch</code> peut créer un fichier vide.'], solution:'mkdir travail/rapports\ntouch travail/rapports/bilan.txt\nls -l travail/rapports', tip:'Un fichier vide a une taille de 0 octet dans la sortie de <code>ls -l</code>.'},
  {id:'04', title:'Copier ou déplacer ?', subtitle:'Garder une source et renommer un fichier', time:'5 min', tags:['cp','mv'], token:'DEPLACER-04', scenario:'Tu veux placer une copie des consignes dans les rapports, puis donner un nom plus précis à ton bilan vide.', steps:['Copie <code>donnees/notes/consignes.txt</code> vers <code>travail/rapports/consignes.txt</code>.','Renomme <code>travail/rapports/bilan.txt</code> en <code>synthese.txt</code>.','Contrôle que l’original des consignes existe toujours et que <code>bilan.txt</code> a disparu.'], hints:['<code>cp</code> conserve la source ; <code>mv</code> déplace ou renomme.','Pour renommer, source et destination se trouvent dans le même dossier.'], solution:'cp donnees/notes/consignes.txt travail/rapports/consignes.txt\nmv travail/rapports/bilan.txt travail/rapports/synthese.txt\nls travail/rapports donnees/notes', tip:'Avant un <code>mv</code>, vérifie le chemin cible : une erreur peut déplacer le fichier ailleurs que prévu.'},
  {id:'05', title:'Espaces et fichiers cachés', subtitle:'Protéger les noms qui surprennent le shell', time:'6 min', tags:['ls -a','guillemets','cp'], token:'ESPACES-05', scenario:'Le dossier <code>Projet Alpha</code> contient un fichier dont le nom comporte un espace et un autre qui commence par un point.', steps:['Affiche tous les fichiers de <code>donnees/Projet Alpha</code>, même les fichiers cachés.','Copie <code>.secret</code> vers <code>travail/rapports/secret.txt</code>.','Copie <code>compte rendu.txt</code> vers <code>travail/rapports/compte-rendu.txt</code>.'], hints:['<code>ls -a</code> affiche aussi les noms commençant par un point.','Entoure un chemin contenant des espaces avec des guillemets.'], solution:'ls -a "donnees/Projet Alpha"\ncp "donnees/Projet Alpha/.secret" travail/rapports/secret.txt\ncp "donnees/Projet Alpha/compte rendu.txt" travail/rapports/compte-rendu.txt', tip:'Un espace non protégé sépare les arguments d’une commande. Les guillemets gardent le chemin entier.'},
  {id:'06', title:'Un motif, trois fichiers', subtitle:'Sélectionner avec les jokers du shell', time:'5 min', tags:['*','mkdir','cp'], token:'MOTIF-06', scenario:'Tu dois récupérer uniquement les factures texte de 2026 : ni celle de 2025, ni le bilan CSV.', steps:['Crée <code>travail/factures</code>.','Copie en une seule commande tous les fichiers <code>2026-*.txt</code> depuis <code>donnees/factures</code>.','Vérifie que le dossier cible contient exactement trois fichiers.'], hints:['Le joker <code>*</code> remplace zéro ou plusieurs caractères dans un nom.','Le motif est <code>donnees/factures/2026-*.txt</code>. Teste-le d’abord avec <code>echo</code>.'], solution:'mkdir travail/factures\necho donnees/factures/2026-*.txt\ncp donnees/factures/2026-*.txt travail/factures/\nls travail/factures', tip:'Le shell développe le joker avant d’appeler <code>cp</code>. <code>echo</code> permet de prévisualiser la sélection.'},
  {id:'07', title:'Écrire et ajouter', subtitle:'Rediriger la sortie d’une commande', time:'5 min', tags:['echo','>','>>'], token:'FLUX-07', scenario:'Tu veux fabriquer un petit fichier texte directement depuis le terminal.', steps:['Écris <code>Linux se pratique.</code> dans <code>reponses/07-message.txt</code>.','Ajoute ensuite <code>Linux se retient.</code> sur la ligne suivante, sans effacer la première.','Affiche le résultat avec <code>cat</code>.'], hints:['<code>></code> crée ou remplace le fichier cible.','<code>>></code> ajoute à la fin du fichier ; <code>echo</code> écrit du texte sur la sortie standard.'], solution:'echo "Linux se pratique." > reponses/07-message.txt\necho "Linux se retient." >> reponses/07-message.txt\ncat reponses/07-message.txt', tip:'Avant une redirection avec <code>></code>, assure-toi que tu peux remplacer le fichier : son ancien contenu sera perdu.'},
  {id:'08', title:'Compter les erreurs', subtitle:'Relier deux commandes avec un tuyau', time:'6 min', tags:['grep','|','wc -l'], token:'TUYAU-08', scenario:'Le journal du serveur est trop long à lire ligne par ligne. Tu dois compter ses messages marqués <code>ERREUR</code>.', steps:['Cherche les lignes contenant <code>ERREUR</code> dans <code>donnees/logs/serveur.log</code>.','Transmets ces lignes à une commande qui les compte.','Enregistre seulement le nombre dans <code>reponses/08-erreurs.txt</code>.'], hints:['<code>grep "ERREUR" fichier</code> affiche les lignes correspondantes.','<code>wc -l</code> compte les lignes reçues. Le tuyau <code>|</code> relie la sortie de la première commande à l’entrée de la seconde.'], solution:'grep "ERREUR" donnees/logs/serveur.log | wc -l > reponses/08-erreurs.txt\ncat reponses/08-erreurs.txt', tip:'Lis un pipeline de gauche à droite : sélectionner les lignes, les compter, enregistrer le résultat.'},
  {id:'09', title:'Deux filtres successifs', subtitle:'Trouver les erreurs d’une date précise', time:'6 min', tags:['grep','|','>'], token:'FILTRE-09', scenario:'On ne t’a demandé que les erreurs du 21 septembre 2026. Le journal contient aussi d’autres dates et niveaux de message.', steps:['Ne conserve que les lignes du <code>2026-09-21</code>.','Parmi elles, ne garde que les lignes <code>ERREUR</code>.','Écris ces lignes dans <code>reponses/09-erreurs-21.txt</code>.'], hints:['Tu peux chaîner deux commandes <code>grep</code>.','Le deuxième <code>grep</code> lit la sortie du premier grâce à <code>|</code>.'], solution:'grep "2026-09-21" donnees/logs/serveur.log | grep "ERREUR" > reponses/09-erreurs-21.txt\ncat reponses/09-erreurs-21.txt', tip:'Après chaque étape d’un pipeline, tu peux exécuter seulement sa partie gauche pour voir les données intermédiaires.'},
  {id:'10', title:'Combien de familles ?', subtitle:'Extraire, trier et dédupliquer', time:'8 min', tags:['cut','sort','uniq','wc'], token:'COLONNES-10', scenario:'L’annuaire contient plusieurs personnes de la même famille. Tu veux connaître le nombre de noms de famille distincts.', steps:['Observe la structure de <code>donnees/annuaire.txt</code> : le nom est la première colonne, séparée par un espace.','Extrais les noms, trie-les puis supprime les doublons.','Enregistre uniquement leur nombre dans <code>reponses/10-noms.txt</code>.'], hints:['<code>cut -d " " -f 1</code> sélectionne la première colonne séparée par un espace.','<code>uniq</code> ne supprime que les doublons voisins : trie avant avec <code>sort</code>.'], solution:'cut -d " " -f 1 donnees/annuaire.txt | sort | uniq | wc -l > reponses/10-noms.txt\ncat reponses/10-noms.txt', tip:'<code>sort -u</code> peut remplacer <code>sort | uniq</code>, mais séparer les étapes aide à comprendre le flux.'},
  {id:'11', title:'Chercher dans une arborescence', subtitle:'Trouver les fichiers par leur nom', time:'6 min', tags:['find','-name','-type'], token:'TROUVER-11', scenario:'Des journaux sont rangés à plusieurs endroits sous <code>donnees</code>. Tu dois obtenir la liste complète de leurs chemins.', steps:['Recherche tous les fichiers dont le nom finit par <code>.log</code> sous <code>donnees</code>.','Trie les chemins trouvés et enregistre-les dans <code>reponses/11-logs.txt</code>.','Le résultat doit contenir deux chemins.'], hints:['<code>find donnees -type f -name "*.log"</code> cherche des fichiers ordinaires.','Mets le motif entre guillemets : il doit être interprété par <code>find</code>, pas développé à l’avance par le shell.'], solution:'find donnees -type f -name "*.log" | sort > reponses/11-logs.txt\ncat reponses/11-logs.txt', tip:'Ici, <code>*.log</code> est un motif transmis à <code>find</code>. Sans guillemets, le shell pourrait le développer trop tôt.'},
  {id:'12', title:'Rendre un script exécutable', subtitle:'Lire et modifier les droits', time:'7 min', tags:['ls -l','chmod','./'], token:'DROITS-12', scenario:'Un script de démonstration est fourni. Tu veux le garder intact et exécuter une copie de travail.', steps:['Copie <code>donnees/bonjour.sh</code> vers <code>travail/bonjour.sh</code>.','Observe ses droits avec <code>ls -l</code>.','Ajoute le droit d’exécution pour le propriétaire, puis lance <code>./travail/bonjour.sh</code>.'], hints:['<code>chmod u+x fichier</code> ajoute le droit d’exécution à l’utilisateur propriétaire.','<code>./</code> indique au shell d’exécuter un fichier à partir du dossier courant.'], solution:'cp donnees/bonjour.sh travail/bonjour.sh\nls -l travail/bonjour.sh\nchmod u+x travail/bonjour.sh\n./travail/bonjour.sh', tip:'Les trois groupes de droits affichés par <code>ls -l</code> concernent le propriétaire, le groupe et les autres utilisateurs.'},
  {id:'13', title:'Emballer le travail', subtitle:'Créer et inspecter une archive', time:'7 min', tags:['tar','-czf','-tzf'], token:'ARCHIVE-13', scenario:'Tu dois transmettre tous les rapports dans un seul fichier compressé, en conservant le dossier qui les contient.', steps:['Crée une archive <code>travail/rapports.tar.gz</code> contenant le dossier <code>rapports</code>.','Affiche la liste des fichiers de l’archive sans l’extraire.','Vérifie la présence de <code>consignes.txt</code> et <code>synthese.txt</code>.'], hints:['<code>tar -czf archive.tar.gz dossier</code> crée une archive compressée.','Depuis la racine de l’atelier, <code>tar -czf travail/rapports.tar.gz -C travail rapports</code> archive le dossier avec le bon chemin.'], solution:'tar -czf travail/rapports.tar.gz -C travail rapports\ntar -tzf travail/rapports.tar.gz', tip:'<code>tar -tzf</code> permet de voir le contenu avant extraction ; <code>-xzf</code> sert à extraire.'},
  {id:'14', title:'Un motif dans les lignes', subtitle:'Premiers pas avec les expressions régulières', time:'8 min', tags:['grep -E','^','.*','$'], token:'REGEX-14', scenario:'Dans l’annuaire, tu cherches les lignes dont le nom commence par <code>B</code> et dont le numéro finit par <code>7</code>.', steps:['Utilise <code>grep -E</code> sur <code>donnees/annuaire.txt</code>.','Décris « commence par B, puis n’importe quels caractères, et finit par 7 ».','Enregistre les lignes dans <code>reponses/14-regex.txt</code>.'], hints:['Dans une expression régulière, <code>^</code> marque le début de la ligne et <code>$</code> sa fin.','<code>.*</code> signifie « zéro ou plusieurs caractères quelconques ». Ce motif n’obéit pas aux mêmes règles que les jokers des noms de fichiers.'], solution:'grep -E "^B.*7$" donnees/annuaire.txt > reponses/14-regex.txt\ncat reponses/14-regex.txt', tip:'Teste un motif avec <code>grep</code> avant d’ajouter la redirection, pour voir les lignes sélectionnées.'},
  {id:'15', title:'Nettoyer avec prudence', subtitle:'Supprimer uniquement le fichier voulu', time:'5 min', tags:['ls -l','rm','ls'], token:'NETTOYER-15', scenario:'Un brouillon fourni dans <code>travail</code> n’a plus d’utilité. Tu dois le supprimer sans toucher aux rapports, aux factures ou aux données sources.', steps:['Affiche le chemin du dossier courant avec <code>pwd</code>.','Vérifie que <code>travail/brouillon.tmp</code> existe avec <code>ls -l</code>.','Supprime uniquement ce fichier, puis vérifie qu’il n’apparaît plus dans <code>travail</code>.'], hints:['<code>rm fichier</code> supprime un fichier. Ici, donne le chemin précis plutôt qu’un joker.','Après <code>rm</code>, <code>ls travail</code> doit encore montrer tes rapports, factures et le script.'], solution:'pwd\nls -l travail/brouillon.tmp\nrm travail/brouillon.tmp\nls travail', tip:'<code>rm</code> ne passe généralement pas par une corbeille. Évite les jokers tant que tu ne sais pas exactement quels fichiers ils désignent.'},
  {"id":"16","title":"Un raccourci qui vit","subtitle":"Créer un lien symbolique relatif","time":"7 min","tags":["ln -s","readlink","ls -l"],"token":"LIEN-16","scenario":"Une consigne doit rester à son emplacement d’origine, tout en étant facile à consulter depuis <code>travail</code>.","steps":["Crée un lien symbolique <code>travail/consignes-lien.txt</code> vers <code>donnees/notes/consignes.txt</code>.","Utilise un chemin cible relatif au dossier qui contient le lien.","Contrôle le résultat avec <code>ls -l</code> et <code>cat</code>."],"hints":["<code>ln -s cible lien</code> crée un lien symbolique. La cible est interprétée à partir du dossier du lien.","Depuis <code>travail</code>, remonte d’un niveau avec <code>..</code> puis entre dans <code>donnees/notes</code>."],"solution":"ln -s ../donnees/notes/consignes.txt travail/consignes-lien.txt\nls -l travail/consignes-lien.txt\ncat travail/consignes-lien.txt","tip":"Un lien symbolique peut devenir « cassé » si sa cible est déplacée. <code>readlink</code> affiche son chemin cible."},
  {"id":"17","title":"Un dossier privé","subtitle":"Comprendre les droits 700 et 600","time":"8 min","tags":["chmod","stat","ls -ld"],"token":"PRIVE-17","scenario":"Une copie de configuration doit être lisible seulement par son propriétaire. Dans cet exercice, on règle les droits sur un dossier de travail.","steps":["Crée <code>travail/prive</code> et copie-y <code>donnees/config/app.conf</code>.","Donne au dossier les droits <code>700</code> et au fichier <code>600</code>.","Inspecte les droits avec <code>stat</code> ou <code>ls -ld</code>."],"hints":["<code>7</code> = lecture + écriture + traversée/exécution ; <code>6</code> = lecture + écriture.","<code>chmod 700 travail/prive</code> et <code>chmod 600 travail/prive/app.conf</code> règlent les deux objets séparément."],"solution":"mkdir travail/prive\ncp donnees/config/app.conf travail/prive/app.conf\nchmod 700 travail/prive\nchmod 600 travail/prive/app.conf\nstat -c \"%a %n\" travail/prive travail/prive/app.conf","tip":"Pour un dossier, <code>x</code> autorise la traversée. Les droits du dossier et du fichier jouent des rôles différents."},
  {"id":"18","title":"Où part l’espace disque ?","subtitle":"Distinguer du et df","time":"6 min","tags":["du","df","cut"],"token":"DISQUE-18","scenario":"Un dossier semble grossir. Tu veux mesurer son espace occupé, puis voir la place disponible sur le système de fichiers.","steps":["Affiche la taille de <code>donnees</code> avec <code>du -sh</code>.","Affiche l’espace disponible sur le système de fichiers courant avec <code>df -h .</code>.","Enregistre le nombre de kilo-octets occupés par <code>donnees</code> dans <code>reponses/18-ko.txt</code>."],"hints":["<code>du -sk donnees</code> produit une taille en Ko suivie du nom du dossier.","La sortie de <code>du -sk</code> sépare les champs par une tabulation. <code>cut -f 1</code> récupère la taille."],"solution":"du -sh donnees\ndf -h .\ndu -sk donnees | cut -f 1 > reponses/18-ko.txt","tip":"<code>du</code> mesure le contenu d’un dossier ; <code>df</code> montre la capacité et l’espace libre d’un système de fichiers."},
  {"id":"19","title":"Prouver qu’un fichier est intact","subtitle":"Calculer et vérifier une empreinte SHA-256","time":"7 min","tags":["sha256sum","-c"],"token":"EMPREINTE-19","scenario":"Avant et après un transfert, une empreinte permet de vérifier que les octets d’un fichier n’ont pas changé.","steps":["Calcule l’empreinte SHA-256 de <code>donnees/notes/consignes.txt</code> et enregistre-la dans <code>reponses/19-hash.txt</code>.","Vérifie ensuite cette empreinte avec l’option <code>-c</code>.","Observe que le nom du fichier fait partie de la ligne de contrôle."],"hints":["<code>sha256sum fichier</code> affiche l’empreinte et le chemin.","Redirige la sortie avec <code>></code>, puis lance <code>sha256sum -c reponses/19-hash.txt</code>."],"solution":"sha256sum donnees/notes/consignes.txt > reponses/19-hash.txt\nsha256sum -c reponses/19-hash.txt","tip":"Une empreinte identique indique que les octets sont les mêmes. Elle ne prouve pas à elle seule qui a créé le fichier."},
  {"id":"20","title":"Sauvegarder puis restaurer","subtitle":"Vérifier une archive par extraction","time":"9 min","tags":["tar -czf","tar -xzf","cmp"],"token":"RESTAURER-20","scenario":"Une sauvegarde n’est utile que si l’on sait la relire. Tu vas archiver le dossier <code>notes</code> puis le restaurer dans un emplacement séparé.","steps":["Crée <code>travail/sauvegarde-notes.tar.gz</code> à partir du dossier <code>donnees/notes</code>.","Crée <code>travail/restauration</code> puis extrais-y l’archive.","Compare les fichiers restaurés avec les originaux à l’aide de <code>cmp</code>."],"hints":["<code>tar -czf travail/sauvegarde-notes.tar.gz -C donnees notes</code> garde le nom du dossier dans l’archive.","<code>tar -xzf archive -C dossier</code> extrait vers le dossier choisi ; <code>cmp</code> est silencieux si les fichiers sont identiques."],"solution":"tar -czf travail/sauvegarde-notes.tar.gz -C donnees notes\nmkdir travail/restauration\ntar -xzf travail/sauvegarde-notes.tar.gz -C travail/restauration\ncmp donnees/notes/consignes.txt travail/restauration/notes/consignes.txt","tip":"Une restauration de test révèle les archives incomplètes, les chemins inattendus et les fichiers illisibles."},
  {"id":"21","title":"Lire la fin d’un journal","subtitle":"Parcourir et extraire les dernières lignes","time":"5 min","tags":["less","tail -n"],"token":"FIN-21","scenario":"Lors d’un incident, les dernières lignes d’un journal sont souvent les premières à consulter.","steps":["Parcours <code>donnees/logs/incidents.log</code> avec <code>less</code> ; quitte avec <code>q</code>.","Enregistre seulement ses trois dernières lignes dans <code>reponses/21-fin.txt</code>.","Vérifie le résultat avec <code>cat</code>."],"hints":["<code>tail</code> lit la fin d’un fichier.","<code>tail -n 3 fichier > destination</code> extrait trois lignes."],"solution":"less donnees/logs/incidents.log\ntail -n 3 donnees/logs/incidents.log > reponses/21-fin.txt\ncat reponses/21-fin.txt","tip":"<code>tail -f</code> suit un journal qui grandit en direct ; termine le suivi avec Ctrl-C."},
  {"id":"22","title":"Voir autour d’une erreur","subtitle":"Numéros de ligne et contexte grep","time":"7 min","tags":["grep -n","-C 1"],"token":"CONTEXTE-22","scenario":"La ligne d’erreur seule ne suffit pas toujours : les lignes voisines donnent parfois la cause et la suite.","steps":["Cherche <code>ERREUR</code> dans <code>donnees/logs/incidents.log</code>.","Affiche les numéros de ligne et une ligne de contexte avant et après chaque résultat.","Enregistre le résultat dans <code>reponses/22-contexte.txt</code>."],"hints":["<code>grep -n</code> ajoute les numéros de ligne.","<code>-C 1</code> ajoute une ligne de contexte de chaque côté."],"solution":"grep -n -C 1 \"ERREUR\" donnees/logs/incidents.log > reponses/22-contexte.txt\nless reponses/22-contexte.txt","tip":"Les options <code>-A</code> et <code>-B</code> affichent seulement le contexte après ou avant une correspondance."},
  {"id":"23","title":"Modifier une copie de configuration","subtitle":"Substituer une ligne avec sed","time":"8 min","tags":["sed","s/ancien/nouveau/",">"],"token":"CONFIG-23","scenario":"Le fichier source est en mode debug. Tu dois produire une variante « production » sans modifier l’original.","steps":["Lis <code>donnees/config/app.conf</code>.","Remplace uniquement la ligne <code>MODE=debug</code> par <code>MODE=production</code>.","Enregistre le résultat dans <code>travail/app.conf</code> et vérifie que les autres lignes sont intactes."],"hints":["<code>sed</code> écrit le résultat sur la sortie standard ; sans <code>-i</code>, il ne modifie pas la source.","<code>sed \"s/^MODE=debug$/MODE=production/\" source > destination</code> cible la ligne entière."],"solution":"sed \"s/^MODE=debug$/MODE=production/\" donnees/config/app.conf > travail/app.conf\ndiff -u donnees/config/app.conf travail/app.conf","tip":"Pour une configuration, travailler sur une copie facilite le contrôle avec <code>diff</code> avant de remplacer un fichier réel."},
  {"id":"24","title":"Compter par service","subtitle":"Regrouper des événements avec awk","time":"10 min","tags":["awk","tableau","sort"],"token":"SERVICES-24","scenario":"Le journal mélange les événements de plusieurs services. Tu veux connaître le nombre d’erreurs de chacun.","steps":["Repère les colonnes : date, heure, service, niveau et message.","Compte les lignes <code>ERREUR</code> pour chaque service.","Enregistre les résultats sous la forme <code>service nombre</code>, triés par nom, dans <code>reponses/24-services.txt</code>."],"hints":["Dans <code>awk</code>, <code>$3</code> est le service et <code>$4</code> le niveau.","Un tableau <code>n[$3]++</code> compte par service. Parcours-le dans <code>END</code>, puis trie la sortie avec <code>sort</code>."],"solution":"awk '$4==\"ERREUR\" {n[$3]++} END {for (s in n) print s, n[s]}' donnees/logs/incidents.log | sort > reponses/24-services.txt\ncat reponses/24-services.txt","tip":"<code>awk</code> traite les lignes et les colonnes. C’est pratique pour une analyse rapide de journaux structurés."},
  {"id":"25","title":"Quels hôtes sont indisponibles ?","subtitle":"Filtrer un inventaire CSV","time":"8 min","tags":["awk -F,","sort"],"token":"HOTES-25","scenario":"L’inventaire indique l’état de chaque machine. Tu dois isoler les noms des hôtes marqués <code>DOWN</code>.","steps":["Observe l’en-tête de <code>donnees/inventaire.csv</code>.","Extrais la première colonne des lignes dont la troisième colonne vaut <code>DOWN</code>.","Trie les noms et enregistre-les dans <code>reponses/25-hotes.txt</code>."],"hints":["<code>awk -F,</code> utilise la virgule comme séparateur de colonnes.","La condition <code>NR>1 && $3==\"DOWN\"</code> ignore l’en-tête et garde les machines arrêtées."],"solution":"awk -F, 'NR>1 && $3==\"DOWN\" {print $1}' donnees/inventaire.csv | sort > reponses/25-hotes.txt\ncat reponses/25-hotes.txt","tip":"Un CSV simple se lit avec <code>awk -F,</code>. Pour des champs entre guillemets contenant des virgules, il faut un véritable parseur CSV."},
  {"id":"26","title":"Observer son shell","subtitle":"Identifier un processus et son PID","time":"7 min","tags":["ps","$$","PID"],"token":"PROCESSUS-26","scenario":"Quand un programme se bloque, son identifiant de processus permet de l’observer puis, si nécessaire, de l’arrêter.","steps":["Assure-toi d’être dans un shell Bash ; lance <code>bash</code> si nécessaire.","Affiche ton PID avec <code>echo $$</code>.","Enregistre le PID et le nom de ton shell dans <code>reponses/26-shell.txt</code> avec <code>ps</code>."],"hints":["Dans Bash, <code>$$</code> contient le PID du shell courant.","<code>ps -p $$ -o pid=,comm=</code> affiche seulement le PID et le nom de la commande."],"solution":"echo $$\nps -p $$ -o pid=,comm= > reponses/26-shell.txt\ncat reponses/26-shell.txt","tip":"Un PID identifie une instance de programme. Plusieurs processus peuvent avoir le même nom, mais pas le même PID à un instant donné."},
  {"id":"27","title":"Lancer et arrêter un processus","subtitle":"Job en arrière-plan et signal de terminaison","time":"8 min","tags":["&","$!","ps","kill"],"token":"SIGNAL-27","scenario":"Tu vas lancer un processus inoffensif en arrière-plan, retrouver son PID puis l’arrêter proprement.","steps":["Lance <code>sleep 300</code> en arrière-plan et enregistre son PID dans <code>travail/sleep.pid</code>.","Vérifie sa présence avec <code>ps -p</code>.","Envoie-lui le signal de terminaison avec <code>kill</code>, puis vérifie qu’il ne tourne plus."],"hints":["Le caractère <code>&</code> lance en arrière-plan ; <code>$!</code> contient le PID du dernier job lancé.","<code>kill \"$(cat travail/sleep.pid)\"</code> demande au processus identifié de se terminer."],"solution":"sleep 300 &\necho $! > travail/sleep.pid\nps -p \"$(cat travail/sleep.pid)\"\nkill \"$(cat travail/sleep.pid)\"\nps -p \"$(cat travail/sleep.pid)\"","tip":"<code>kill</code> envoie par défaut SIGTERM, que le programme peut gérer. Évite <code>kill -9</code> sauf nécessité."},
  {"id":"28","title":"Une variable pour configurer","subtitle":"Exporter une variable d’environnement","time":"6 min","tags":["export","printenv"],"token":"ENVIRONNEMENT-28","scenario":"Les applications utilisent souvent des variables d’environnement pour choisir leur mode de fonctionnement.","steps":["Dans ton terminal, définis et exporte <code>APP_ENV</code> avec la valeur <code>formation</code>.","Vérifie sa valeur avec <code>printenv</code>.","Enregistre cette valeur dans <code>reponses/28-env.txt</code>."],"hints":["<code>export NOM=valeur</code> crée une variable transmise aux processus enfants.","<code>printenv APP_ENV > reponses/28-env.txt</code> enregistre sa valeur."],"solution":"export APP_ENV=formation\nprintenv APP_ENV > reponses/28-env.txt\ncat reponses/28-env.txt","tip":"Une variable définie dans le shell disparaît à la fermeture de la session, sauf si elle est ajoutée à une configuration du shell."},
  {"id":"29","title":"Où est la commande ?","subtitle":"Explorer PATH sans deviner les chemins","time":"6 min","tags":["PATH","command -v","type"],"token":"CHEMIN-29","scenario":"Avant de diagnostiquer une commande introuvable, il faut comprendre comment le shell retrouve les exécutables.","steps":["Affiche <code>$PATH</code> pour voir les dossiers de recherche.","Trouve le chemin de l’exécutable <code>bash</code> avec <code>command -v</code>.","Enregistre ce chemin dans <code>reponses/29-bash.txt</code>."],"hints":["<code>echo \"$PATH\"</code> affiche la liste des dossiers séparés par des deux-points.","<code>command -v bash > reponses/29-bash.txt</code> enregistre le chemin trouvé."],"solution":"echo \"$PATH\"\ncommand -v bash > reponses/29-bash.txt\ncat reponses/29-bash.txt","tip":"<code>type nom</code> indique si un nom est une commande interne, un alias ou un programme trouvé dans PATH."},
  {"id":"30","title":"Capturer une erreur","subtitle":"Séparer sortie normale et sortie d’erreur","time":"6 min","tags":["stdout","stderr","2>"],"token":"ERREUR-30","scenario":"Une commande échoue. En administration, il est utile de conserver son message d’erreur sans mélanger les flux.","steps":["Essaie de lister le fichier inexistant <code>donnees/introuvable</code>.","Redirige uniquement la sortie d’erreur vers <code>reponses/30-stderr.txt</code>.","Affiche le fichier obtenu et compare <code>></code> avec <code>2></code>."],"hints":["Le descripteur <code>1</code> est la sortie normale ; <code>2</code> est la sortie d’erreur.","<code>ls donnees/introuvable 2> reponses/30-stderr.txt</code> capture le message d’échec."],"solution":"ls donnees/introuvable 2> reponses/30-stderr.txt\ncat reponses/30-stderr.txt","tip":"Les erreurs apparaissent normalement dans le terminal même lorsque la sortie normale est redirigée avec <code>></code>."},
  {"id":"31","title":"Un script avec un argument","subtitle":"Compter les erreurs de n’importe quel journal","time":"12 min","tags":["bash","$1","grep -c"],"token":"SCRIPT-31","scenario":"Tu répètes souvent la même commande sur plusieurs journaux. Écris un script réutilisable qui reçoit le chemin du journal en argument.","steps":["Crée <code>travail/compter-erreurs.sh</code> dans un éditeur.","Le script doit afficher seulement le nombre de lignes contenant <code>ERREUR</code> dans le fichier passé en premier argument.","Teste-le sur <code>serveur.log</code>, <code>incidents.log</code> et <code>archive.log</code> ; le dernier doit afficher zéro."],"hints":["<code>$1</code> est le premier argument. Mets-le entre guillemets pour préserver un chemin contenant des espaces.","<code>grep -c ERREUR \"$1\"</code> compte les lignes. <code>grep</code> renvoie un statut non nul pour zéro résultat, même s’il affiche <code>0</code>."],"solution":"#!/usr/bin/env bash\ngrep -c ERREUR \"$1\" || true","tip":"Un bon script accepte des arguments et fonctionne sur plusieurs fichiers. Le vérificateur le teste avec trois journaux différents."},
  {"id":"32","title":"Décider avec un code de sortie","subtitle":"Valider une configuration en Bash","time":"12 min","tags":["if","grep -q","exit"],"token":"CONDITION-32","scenario":"Un déploiement doit être refusé si la configuration n’est pas en mode production.","steps":["Crée <code>travail/verifier-config.sh</code> : il reçoit un fichier en argument.","S’il contient la ligne exacte <code>MODE=production</code>, affiche <code>OK</code> et termine avec le code 0.","Sinon, affiche <code>KO</code> et termine avec un code non nul. Teste les deux fichiers de <code>donnees/config</code>."],"hints":["<code>grep -q</code> teste la présence d’une ligne sans l’afficher.","Dans Bash : <code>if grep -q \"^MODE=production$\" \"$1\"; then ... else ... fi</code>."],"solution":"#!/usr/bin/env bash\nif grep -q \"^MODE=production$\" \"$1\"; then\n  echo OK\n  exit 0\nelse\n  echo KO\n  exit 1\nfi","tip":"Le code de sortie d’un programme est 0 en cas de succès. <code>echo $?</code> affiche le statut de la dernière commande."},
  {"id":"33","title":"Traiter tous les journaux","subtitle":"Une boucle Bash et un rapport","time":"13 min","tags":["for","basename","grep -c"],"token":"BOUCLE-33","scenario":"Tu veux connaître le nombre d’erreurs par fichier journal sans copier-coller la même commande.","steps":["Crée <code>travail/rapport-logs.sh</code> qui reçoit le chemin d’un dossier.","Pour chaque fichier <code>*.log</code> de ce dossier, affiche <code>nom-du-fichier nombre</code>.","Teste-le avec <code>donnees/logs</code> : il doit produire trois lignes."],"hints":["Une boucle <code>for fichier in \"$1\"/*.log; do ...; done</code> parcourt les journaux.","<code>basename \"$fichier\"</code> garde le nom court ; <code>grep -c</code> fournit le compte."],"solution":"#!/usr/bin/env bash\nfor fichier in \"$1\"/*.log; do\n  nombre=$(grep -c ERREUR \"$fichier\")\n  printf \"%s %s\\n\" \"$(basename \"$fichier\")\" \"$nombre\"\ndone","tip":"Teste toujours une boucle sur un petit jeu de fichiers avant de l’utiliser sur une grande arborescence."},
  {"id":"34","title":"Un script de sauvegarde","subtitle":"Arguments, échec clair et archive portable","time":"15 min","tags":["set -euo pipefail","tar","test"],"token":"BACKUP-34","scenario":"Tu dois automatiser l’archivage d’un dossier et signaler clairement si le dossier source n’existe pas.","steps":["Crée <code>travail/sauvegarder.sh</code> : argument 1 = dossier source, argument 2 = archive cible.","Le script doit refuser une source absente avec un code non nul.","Utilise-le pour créer <code>travail/auto-notes.tar.gz</code> à partir de <code>donnees/notes</code>, puis liste l’archive."],"hints":["<code>[[ -d \"$1\" ]]</code> teste l’existence d’un dossier ; <code>exit 2</code> signale une erreur.","<code>tar -czf \"$2\" -C \"$(dirname \"$1\")\" \"$(basename \"$1\")\"</code> conserve le nom du dossier dans l’archive."],"solution":"#!/usr/bin/env bash\nset -euo pipefail\nif [[ ! -d \"$1\" ]]; then\n  echo \"Dossier source absent\" >&2\n  exit 2\nfi\ntar -czf \"$2\" -C \"$(dirname \"$1\")\" \"$(basename \"$1\")\"\n# bash travail/sauvegarder.sh donnees/notes travail/auto-notes.tar.gz","tip":"Une sauvegarde automatisée doit échouer visiblement si la source manque. Un code de succès trompeur est dangereux."},
  {"id":"35","title":"Enquête complète","subtitle":"Rédiger un mini rapport d’incident","time":"18 min","tags":["grep","awk","sort","tail"],"token":"INCIDENT-35","scenario":"Le responsable d’exploitation veut une réponse rapide sur <code>incidents.log</code> : combien d’erreurs, quel service en a le plus et quand s’est produite la dernière ?","steps":["Crée <code>reponses/35-incident.txt</code> avec trois lignes <code>total=...</code>, <code>service=...</code> et <code>derniere=...</code>.","Pour <code>derniere</code>, indique la date, l’heure et le service de la dernière ligne <code>ERREUR</code>.","Utilise tes commandes de recherche et de traitement ; évite de compter à la main."],"hints":["<code>grep -c</code> compte les erreurs ; <code>tail -n 1</code> trouve la dernière ligne correspondante.","Pour le service dominant, réutilise le regroupement avec <code>awk</code>, trie les comptes numériquement dans l’ordre décroissant avec <code>sort -nr</code>."],"solution":"printf \"total=%s\\n\" \"$(grep -c ERREUR donnees/logs/incidents.log)\" > reponses/35-incident.txt\nprintf \"service=%s\\n\" \"$(awk '$4==\"ERREUR\" {n[$3]++} END {for(s in n) print n[s],s}' donnees/logs/incidents.log | sort -nr | head -n 1 | cut -d \" \" -f 2)\" >> reponses/35-incident.txt\nprintf \"derniere=%s\\n\" \"$(grep ERREUR donnees/logs/incidents.log | tail -n 1 | cut -d \" \" -f 1-3)\" >> reponses/35-incident.txt","tip":"Un rapport court et reproductible aide à distinguer les faits observés des hypothèses sur la cause."},
  {"id":"36","title":"Identifier la distribution","subtitle":"Lire /etc/os-release sans supposer la version","time":"6 min","tags":["/etc/os-release","source"],"token":"SYSTEME-36","scenario":"Les commandes de gestion varient selon la distribution. Commence par identifier précisément le système de la VM.","steps":["Lis <code>/etc/os-release</code>.","Dans Bash, charge ce fichier puis écris <code>ID VERSION_ID</code> sur une seule ligne dans <code>reponses/36-os.txt</code>.","Repère aussi l’architecture avec <code>uname -m</code>."],"hints":["<code>. /etc/os-release</code> charge les variables <code>ID</code> et <code>VERSION_ID</code> dans le shell courant.","<code>printf \"%s %s\\n\" \"$ID\" \"$VERSION_ID\"</code> écrit les deux valeurs."],"solution":". /etc/os-release\nprintf \"%s %s\\n\" \"$ID\" \"$VERSION_ID\" > reponses/36-os.txt\nuname -m","tip":"Sur AlmaLinux, <code>ID</code> vaut normalement <code>almalinux</code>. La version précise dépend de la VM."},
  {"id":"37","title":"Qui fournit Bash ?","subtitle":"Inspecter un paquet RPM et les dépôts DNF","time":"9 min","tags":["rpm -q","rpm -qf","dnf repolist"],"token":"PAQUET-37","scenario":"Avant de modifier un logiciel, identifie le paquet installé et les dépôts activés. Cette mission ne demande aucune installation.","steps":["Lance <code>rpm -q bash</code> et enregistre sa réponse dans <code>reponses/37-paquet.txt</code>.","Trouve le paquet propriétaire de l’exécutable Bash avec <code>rpm -qf \"$(command -v bash)\"</code>.","Affiche les dépôts activés avec <code>dnf repolist --enabled</code>."],"hints":["<code>rpm -q paquet</code> interroge la base locale des paquets installés.","<code>rpm -q bash > reponses/37-paquet.txt</code> produit une ligne qui inclut la version et l’architecture."],"solution":"rpm -q bash > reponses/37-paquet.txt\nrpm -qf \"$(command -v bash)\"\ndnf repolist --enabled","tip":"<code>rpm</code> interroge les paquets installés ; <code>dnf</code> gère les dépôts et les opérations de paquets. Ici, on consulte seulement."},
  {"id":"38","title":"Lire une unité systemd","subtitle":"Comprendre User, ExecStart et Restart","time":"9 min","tags":["systemctl","grep -E","unit file"],"token":"UNITE-38","scenario":"Un service ne démarre pas. Avant de relancer quoi que ce soit, lis son unité et identifie les paramètres qui contrôlent son lancement.","steps":["Lis l’exemple <code>donnees/services/web.service</code> : il n’est pas installé sur ta VM.","Extrais dans <code>reponses/38-unite.txt</code> les lignes <code>After</code>, <code>User</code>, <code>ExecStart</code> et <code>Restart</code>.","Observe ensuite un vrai service en lecture seule avec <code>systemctl show -p LoadState -p ActiveState systemd-journald.service</code>."],"hints":["<code>grep -E</code> permet de sélectionner plusieurs noms de paramètres avec <code>|</code>.","Le motif <code>^(After|User|ExecStart|Restart)=</code> évite de sélectionner les commentaires."],"solution":"grep -E \"^(After|User|ExecStart|Restart)=\" donnees/services/web.service > reponses/38-unite.txt\nsystemctl show -p LoadState -p ActiveState systemd-journald.service","tip":"<code>systemctl status</code> observe un service ; <code>restart</code> le modifie. Commence toujours par l’état et les journaux."},
  {"id":"39","title":"Interroger le journal système","subtitle":"Découvrir journalctl sans changer la VM","time":"8 min","tags":["journalctl","-n","--disk-usage"],"token":"JOURNAL-39","scenario":"Les services gérés par systemd envoient souvent leurs événements au journal. Tu vas le consulter sans modifier sa configuration.","steps":["Affiche les cinq dernières entrées visibles avec <code>journalctl -n 5 --no-pager</code>.","Observe éventuellement une unité précise avec <code>journalctl -u systemd-journald -n 5 --no-pager</code>.","Enregistre l’occupation disque du journal dans <code>reponses/39-journal.txt</code> avec <code>LANG=C journalctl --disk-usage</code>."],"hints":["<code>-n 5</code> limite le nombre de lignes ; <code>--no-pager</code> évite le défileur interactif.","<code>LANG=C journalctl --disk-usage > reponses/39-journal.txt</code> stabilise la langue du message pour la vérification."],"solution":"journalctl -n 5 --no-pager\njournalctl -u systemd-journald -n 5 --no-pager\nLANG=C journalctl --disk-usage > reponses/39-journal.txt","tip":"Selon les droits de ton compte, le journal peut n’afficher qu’une partie des événements. C’est normal pour un utilisateur non privilégié."},
  {"id":"40","title":"Cartographier les interfaces","subtitle":"Lire adresses et routes réseau","time":"8 min","tags":["ip -br addr","ip route"],"token":"RESEAU-40","scenario":"Quand une machine ne répond pas, commence par relever ses interfaces, adresses et routes avant de soupçonner le service.","steps":["Enregistre la vue courte des interfaces avec <code>ip -br address</code> dans <code>reponses/40-interfaces.txt</code>.","Observe la route par défaut avec <code>ip route</code>.","Repère l’interface <code>lo</code> et explique pourquoi son adresse est locale à la machine."],"hints":["<code>ip -br address</code> affiche une ligne par interface.","L’interface <code>lo</code> est la boucle locale ; elle possède normalement <code>127.0.0.1/8</code>."],"solution":"ip -br address > reponses/40-interfaces.txt\nip route\ngrep \"^lo\" reponses/40-interfaces.txt","tip":"Une interface UP n’implique pas que l’application fonctionne. Adresse, route, écoute réseau et journaux sont des contrôles différents."},
  {"id":"41","title":"Quels ports écoutent ?","subtitle":"Lire les sockets TCP sans les modifier","time":"8 min","tags":["ss -lnt","LISTEN"],"token":"PORTS-41","scenario":"Un service peut être démarré sans écouter sur le port attendu. Il faut comparer son état aux sockets réellement ouvertes.","steps":["Enregistre les sockets TCP en écoute dans <code>reponses/41-ports.txt</code> avec <code>ss -lnt</code>.","Repère les colonnes adresse locale et port.","Compare avec <code>systemctl status sshd</code> si ce service existe sur ta VM ; son absence n’empêche pas la mission."],"hints":["<code>-l</code> garde les sockets en écoute, <code>-n</code> évite la résolution de noms, <code>-t</code> sélectionne TCP.","<code>ss -lnt > reponses/41-ports.txt</code> capture la table. Elle peut être courte sur une VM peu chargée."],"solution":"ss -lnt > reponses/41-ports.txt\ncat reponses/41-ports.txt\nsystemctl status sshd","tip":"Une ligne <code>127.0.0.1:PORT</code> n’est accessible que localement ; une écoute sur <code>0.0.0.0:PORT</code> couvre toutes les interfaces IPv4."},
  {"id":"42","title":"Le contrôle SELinux","subtitle":"Lire le mode de sécurité actif","time":"8 min","tags":["getenforce","ls -Z","firewall-cmd"],"token":"SELINUX-42","scenario":"Sur AlmaLinux, les droits Unix ne sont pas le seul contrôle d’accès : SELinux peut aussi influencer le comportement d’un service.","steps":["Enregistre le mode courant de SELinux dans <code>reponses/42-selinux.txt</code> avec <code>getenforce</code>.","Observe un contexte de sécurité avec <code>ls -Z donnees/notes/consignes.txt</code>.","Si <code>firewall-cmd</code> est présent, regarde son état avec <code>firewall-cmd --state</code> sans changer de règle."],"hints":["<code>getenforce</code> affiche <code>Enforcing</code>, <code>Permissive</code> ou <code>Disabled</code>.","<code>getenforce > reponses/42-selinux.txt</code> enregistre la valeur actuelle."],"solution":"getenforce > reponses/42-selinux.txt\nls -Z donnees/notes/consignes.txt\ncommand -v firewall-cmd && firewall-cmd --state","tip":"Un refus SELinux ne se résout pas en désactivant SELinux. On examine d’abord les contextes et les journaux d’audit."}
];

const cards = [
  {id:'q1', question:'Tu ne sais plus dans quel dossier tu te trouves. Quelle commande lance-tu ?', options:['cd','pwd','ls'], answer:1, explain:'pwd affiche le chemin du dossier courant.'},
  {id:'q2', question:'Depuis atelier-linux, que désigne « ../ » ?', options:['Le dossier courant','Le dossier parent','Le dossier personnel'], answer:1, explain:'.. représente le dossier parent, tandis que . représente le dossier courant.'},
  {id:'q3', question:'Tu veux conserver le fichier source. Quelle commande utilises-tu ?', options:['mv','cp','rm'], answer:1, explain:'cp copie le fichier ; mv le déplace ou le renomme.'},
  {id:'q4', question:'Que fait « > » si le fichier cible existe déjà ?', options:['Ajoute une ligne','Écrase son contenu','Affiche son contenu'], answer:1, explain:'> remplace le contenu. Pour ajouter à la fin, utilise >>.'},
  {id:'q5', question:'Que signifie le « | » entre deux commandes ?', options:['Il transmet la sortie de la première à la seconde','Il enregistre un fichier','Il lance deux terminaux'], answer:0, explain:'Le tuyau transmet la sortie standard d’une commande à l’entrée standard de la suivante.'},
  {id:'q6', question:'Pourquoi trier avant d’utiliser uniq ?', options:['Pour accélérer grep','Pour rendre les doublons voisins','Pour changer les majuscules'], answer:1, explain:'uniq élimine les répétitions consécutives. sort regroupe les lignes identiques.'},
  {id:'q7', question:'Pourquoi écrire -name "*.log" avec des guillemets dans find ?', options:['Pour cacher les fichiers','Pour laisser find interpréter le motif','Pour rechercher un seul fichier'], answer:1, explain:'Les guillemets empêchent le shell de développer le motif avant que find ne le reçoive.'},
  {id:'q8', question:'Que fait « chmod u+x bonjour.sh » ?', options:['Retire l’accès aux autres','Ajoute l’exécution au propriétaire','Exécute le script'], answer:1, explain:'u cible le propriétaire, + ajoute un droit, x est le droit d’exécution.'},
  {id:'q9', question:'Quelle commande montre les fichiers présents dans une archive tar.gz sans extraction ?', options:['tar -tzf','tar -xzf','tar -czf'], answer:0, explain:'t liste, x extrait, c crée ; z traite gzip et f indique le nom de l’archive.'},
  {id:'q10', question:'Dans une expression régulière, que signifie « ^B.*7$ » ?', options:['Un nom de fichier contenant B et 7','Une ligne commençant par B et finissant par 7','Exactement B7'], answer:1, explain:'^ et $ encadrent la ligne ; .* accepte une suite quelconque de caractères.'},
  {"id":"q11","unlock":"16","question":"Un lien symbolique contient quoi ?","options":["Une copie intégrale","Un chemin vers une cible","Une archive compressée"],"answer":1,"explain":"Le lien contient une référence à la cible. Il peut devenir cassé si la cible bouge."},
  {"id":"q12","unlock":"17","question":"Que signifie le mode 700 sur un dossier ?","options":["Tous les utilisateurs peuvent lire","Seul le propriétaire a tous les droits","Le fichier est exécutable par tous"],"answer":1,"explain":"7 donne lecture, écriture et traversée au propriétaire ; 0 retire ces droits au groupe et aux autres."},
  {"id":"q13","unlock":"18","question":"Tu cherches l’espace libre sur le système de fichiers. Quelle commande ?","options":["du -sh","df -h","sha256sum"],"answer":1,"explain":"df indique capacité et espace libre ; du mesure la place occupée par des fichiers ou dossiers."},
  {"id":"q14","unlock":"19","question":"À quoi sert sha256sum -c ?","options":["Compresser un fichier","Vérifier une empreinte enregistrée","Changer les droits"],"answer":1,"explain":"L’option -c recalcule l’empreinte et la compare à celle du fichier de contrôle."},
  {"id":"q15","unlock":"23","question":"Sans option -i, que modifie sed ?","options":["Le fichier source","La sortie produite","Les permissions du fichier"],"answer":1,"explain":"sed produit le texte transformé sur sa sortie standard ; une redirection permet de l’enregistrer."},
  {"id":"q16","unlock":"24","question":"Dans awk, à quoi correspond $3 ?","options":["À la troisième ligne","Au troisième champ","Au code de sortie"],"answer":1,"explain":"awk découpe chaque ligne en champs ; $3 désigne le troisième."},
  {"id":"q17","unlock":"27","question":"À quoi correspond $! juste après une commande lancée avec & ?","options":["Au PID du dernier job en arrière-plan","Au dernier code de sortie","À l’utilisateur courant"],"answer":0,"explain":"$! donne le PID du dernier processus lancé en arrière-plan depuis ce shell."},
  {"id":"q18","unlock":"30","question":"Quelle redirection capture seulement les erreurs ?","options":["> fichier","2> fichier","| fichier"],"answer":1,"explain":"Le descripteur 2 est la sortie d’erreur ; 1 est la sortie normale."},
  {"id":"q19","unlock":"32","question":"Quel code de sortie signale normalement un succès ?","options":["0","1","255"],"answer":0,"explain":"Un programme renvoie 0 en cas de succès, une valeur non nulle en cas d’échec."},
  {"id":"q20","unlock":"37","question":"Sur AlmaLinux, quel outil interroge la base locale des paquets installés ?","options":["rpm","journalctl","ss"],"answer":0,"explain":"rpm -q interroge les paquets installés ; dnf gère les dépôts et les opérations sur les paquets."},
  {"id":"q21","unlock":"38","question":"Quel champ d’une unité systemd indique la commande lancée ?","options":["After","ExecStart","Restart"],"answer":1,"explain":"ExecStart définit la commande de démarrage du service."},
  {"id":"q22","unlock":"39","question":"Quelle option de journalctl limite les résultats aux cinq dernières entrées ?","options":["-n 5","-u 5","-f 5"],"answer":0,"explain":"-n fixe le nombre d’entrées affichées."},
  {"id":"q23","unlock":"41","question":"Que montre ss -lnt ?","options":["Les processus terminés","Les sockets TCP en écoute","Les paquets installés"],"answer":1,"explain":"ss affiche les sockets ; -l filtre les écoutes, -n garde les ports numériques et -t sélectionne TCP."},
  {"id":"q24","unlock":"42","question":"Que signifie le mode SELinux Enforcing ?","options":["Les règles sont appliquées","SELinux est désactivé","Les refus sont seulement journalisés"],"answer":0,"explain":"Enforcing applique les règles ; Permissive journalise les refus sans les imposer."}
];

const lessons = courseLessons;
const archiveUrl = 'https://raw.githubusercontent.com/Darksice/linux/main/atelier-linux.tar.gz';
const ctfModules = [module01, module02];
const ctfArchiveUrl = mod => `https://raw.githubusercontent.com/Darksice/linux/main/${mod.archive}`;

const stateKey = 'linux-pour-de-vrai-v1';
let saved;
try { saved = JSON.parse(localStorage.getItem(stateKey) || '{}'); } catch { saved = {}; }
const state = {done: Array.isArray(saved.done) ? saved.done : [], cards: saved.cards && typeof saved.cards === 'object' ? saved.cards : {}, ctfDone: saved.ctfDone && typeof saved.ctfDone === 'object' ? saved.ctfDone : {}, sidebarHidden: saved.sidebarHidden === true};
let revealed = 0;
let feedback = '';
let quizSession = [];
let quizIndex = 0;
let quizAnswer = null;
let quizMode = 'due';
const ctfActive = {};
const ctfHints = {};
let ctfFeedback = '';
let ctfResetPending = false;

function persist(){try{localStorage.setItem(stateKey,JSON.stringify(state));}catch{}}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function today(){return dateKey(new Date())}
function later(days){const d=new Date();d.setDate(d.getDate()+days);return dateKey(d)}
function unlockedCards(){
  const unlock={q1:'01',q2:'01',q3:'04',q4:'07',q5:'08',q6:'10',q7:'11',q8:'12',q9:'13',q10:'14'};
  return cards.filter(c => state.done.includes(c.unlock || unlock[c.id]));
}
function dueCards(){return unlockedCards().filter(c=>!state.cards[c.id] || state.cards[c.id].due <= today())}
function missedCards(){return unlockedCards().filter(c=>state.cards[c.id]?.wrong === true)}
function ctfCompleted(mod){return Array.isArray(state.ctfDone[mod.id]) ? state.ctfDone[mod.id] : []}
function validateCtfFlag(mod, challenge, input){
  const value=input.trim().toUpperCase();
  if(value!==challenge.flag.toUpperCase())return {valid:false,message:value===challenge.decoy?.toUpperCase()?challenge.decoyFeedback:'Mauvais flag. Vérifie la question, si besoin regarde l\'indice !'};
  if(!Array.isArray(state.ctfDone[mod.id]))state.ctfDone[mod.id]=[];
  if(!state.ctfDone[mod.id].includes(challenge.id))state.ctfDone[mod.id].push(challenge.id);
  persist();
  return {valid:true,message:challenge.success};
}
function resetCtfModule(mod){
  delete state.ctfDone[mod.id];
  for(const key of Object.keys(ctfHints))if(key.startsWith(`${mod.id}-`))delete ctfHints[key];
  ctfActive[mod.id]=0;
  ctfFeedback='';
  ctfResetPending=false;
  persist();
}
function applySidebarState(){
  document.body.classList.toggle('sidebar-hidden',state.sidebarHidden);
  const button=document.getElementById('sidebar-toggle');
  button.setAttribute('aria-expanded',String(!state.sidebarHidden));
  button.setAttribute('aria-label',state.sidebarHidden?'Afficher le menu':'Masquer le menu');
}
function ctfCurrent(mod){
  if(ctfActive[mod.id] === undefined) ctfActive[mod.id] = Math.max(0, mod.challenges.findIndex(c => !ctfCompleted(mod).includes(c.id)));
  return mod.challenges[ctfActive[mod.id]] || mod.challenges[0];
}
function getRoute(){const h=decodeURIComponent(location.hash.slice(1));return h || 'accueil'}
function routeTo(route){location.hash = route; if(getRoute()===route) render()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function terminal(lines){return `<div class="terminal"><div class="terminal-bar"><span class="terminal-dot"></span><span class="terminal-dot"></span><span class="terminal-dot"></span><span class="terminal-title">terminal · VM Linux</span></div><pre>${lines}</pre></div>`}
function missionModule(id){return modules.find(m=>m.missions.includes(id))}

function renderNav(){
  document.getElementById('module-nav').innerHTML=ctfModules.map(mod=>`<button class="module-nav-item ${getRoute()==='module-'+mod.id?'active':''}" data-route="module-${mod.id}" aria-current="${getRoute()==='module-'+mod.id?'page':'false'}"><span class="module-nav-id">${escapeHtml(mod.id)}</span><span class="module-nav-text">${escapeHtml(mod.title)}</span><span class="module-nav-count">${ctfCompleted(mod).length}/${mod.challenges.length}</span></button>`).join('');
  document.getElementById('nav').innerHTML=modules.map(m=>`<div class="nav-group"><div class="nav-group-title">${m.id} · ${m.title}</div>${m.missions.map(id=>{const item=missions.find(x=>x.id===id);return `<button class="nav-item ${getRoute()==='mission-'+id?'active':''}" data-route="mission-${id}" aria-current="${getRoute()==='mission-'+id?'page':'false'}"><span class="nav-index">${id}</span><span>${item.title}</span>${state.done.includes(id)?'<span class="nav-check" aria-label="terminée">✓</span>':''}</button>`}).join('')}</div>`).join('');
  document.getElementById('mission-select').innerHTML=`<option value="">Choisir une mission…</option>${modules.map(m=>`<optgroup label="${m.id} · ${m.title}">${m.missions.map(id=>{const item=missions.find(x=>x.id===id);return `<option value="mission-${id}" ${getRoute()==='mission-'+id?'selected':''}>${id} · ${item.title}${state.done.includes(id)?' ✓':''}</option>`}).join('')}</optgroup>`).join('')}`;
  document.getElementById('progress-side').textContent=`${state.done.length} / ${missions.length} missions`;
  const percent=Math.round(state.done.length/missions.length*100);
  document.getElementById('progress-percent').textContent=`${percent} %`;
  document.getElementById('progress-fill').style.width=`${percent}%`;
  document.getElementById('due-count').textContent=dueCards().length;
}

function renderHome(){
  return `<section class="hero"><div><p class="eyebrow">UN PARCOURS POUR APPRENDRE EN FAISANT</p><h1>Le terminal,<br><em>ça s’apprend.</em></h1><p class="lead">Explore les modules CTF dans ta VM AlmaLinux : une archive par thème, des flags à découvrir et des pièges qui apprennent à lire précisément. Le parcours de ${missions.length} missions reste disponible pendant que nous construisons les modules ensemble.</p></div><div class="hero-card"><h2>Prêt à ouvrir le terminal ?</h2><p>Commence par te repérer, puis apprends à lire et comparer les fichiers dans ta VM AlmaLinux.</p><button class="primary" data-route="module-01">Entrer dans le Module 01 →</button></div></section>
  ${ctfModules.map(mod=>`<section class="ctf-home-card"><div><p class="eyebrow">MODULE CTF · ${escapeHtml(mod.id)}</p><h2>${escapeHtml(mod.id)} · ${escapeHtml(mod.title)}</h2><p>${escapeHtml(mod.description)}</p><div class="ctf-home-meta"><span>${ctfCompleted(mod).length} / ${mod.challenges.length} flags trouvés</span><span>Archive dédiée · indices progressifs</span></div></div><button class="secondary" data-route="module-${escapeHtml(mod.id)}">${ctfCompleted(mod).length?'Reprendre le module':'Commencer le module'} →</button></section>`).join('')}
  <div class="progress-summary"><div><small>TA PROGRESSION</small><br><strong>${state.done.length} mission${state.done.length>1?'s':''} terminée${state.done.length>1?'s':''} sur ${missions.length}</strong></div><button class="secondary" data-view="revision">${dueCards().length?`Réviser ${dueCards().length} carte${dueCards().length>1?'s':''}`:'Voir les révisions'} →</button></div>
  <div class="section-head"><div><p class="eyebrow">PARCOURS EXISTANT</p><h2>${modules.length} étapes, un vrai terminal</h2></div><p>Du premier <code>pwd</code> à l’inspection de SELinux.</p></div>
  <div class="module-grid">${modules.map((m,i)=>`<button class="module-card" data-route="mission-${m.missions[0]}"><div class="module-top"><span class="module-number">ÉTAPE 0${i+1}</span><span class="module-count">${m.missions.filter(id=>state.done.includes(id)).length} / ${m.missions.length} missions</span></div><h3>${m.title} ↗</h3><p>${m.description}</p></button>`).join('')}</div>
  <section class="course-promo"><div><p class="eyebrow">BESOIN D’UNE EXPLICATION ?</p><h2>${lessons.length} fiches de cours express</h2><p>Des commandes, leurs options, des exemples commentés et des exercices. À consulter pendant les missions ou plus tard au travail.</p></div><button class="secondary" data-view="cours">Parcourir les fiches →</button></section>
  <div class="setup" id="installation"><div><p class="eyebrow">AVANT DE COMMENCER</p><h3>Prépare ta VM en deux minutes</h3><p>Télécharge l’archive depuis GitHub dans ta VM Linux, extrais-la puis ouvre le dossier créé. Aucun compte, installation ni droit administrateur n’est nécessaire.</p><a class="primary download-link" href="${archiveUrl}">Télécharger l’atelier (.tar.gz) ↓</a><div class="small-note">L’archive contient les données des missions et le vérificateur local.</div></div><div>${terminal('<span class="comment"># Dans le dossier où se trouve l’archive :</span>\n<span class="prompt">$</span> tar -xzf atelier-linux.tar.gz\n<span class="prompt">$</span> cd atelier-linux\n<span class="prompt">$</span> ls\n<span class="comment"># Tu devrais voir donnees, travail, reponses…</span>')}</div></div>`;
}

function renderCtfModule(mod){
  const done=ctfCompleted(mod);
  const current=ctfCurrent(mod);
  const index=mod.challenges.findIndex(c=>c.id===current.id);
  const key=`${mod.id}-${current.id}`;
  const hintsShown=ctfHints[key] || 0;
  const solved=done.includes(current.id);
  const percent=Math.round(done.length/mod.challenges.length*100);
  return `<div class="breadcrumbs"><button data-route="accueil">Accueil</button><span>›</span><span>Module ${mod.id}</span></div>
  <p class="eyebrow">MODULE ${escapeHtml(mod.id)} · EXPLORATION CTF</p><h1 class="page-title">${escapeHtml(mod.title)}</h1><p class="page-intro">${escapeHtml(mod.description)} ${escapeHtml(mod.intro)}</p>
  <section class="ctf-setup"><div><div class="ctf-setup-top"><span>TON TERRAIN DE JEU</span><span>${done.length} / ${mod.challenges.length} flags</span></div><div class="progress-track"><div class="progress-fill" style="width:${percent}%"></div></div><p>Sur ta machine Linux, télécharge l’archive de ce module depuis GitHub. Extrais-la puis ouvre <code>${escapeHtml(mod.folder)}</code>. Lis bien chaque question avant de répondre.</p><a class="secondary download-link" href="${ctfArchiveUrl(mod)}">Télécharger l’archive du Module ${escapeHtml(mod.id)} ↓</a></div>${terminal(`<span class="prompt">$</span> tar -xzf ${escapeHtml(mod.archive)}\n<span class="prompt">$</span> cd ${escapeHtml(mod.folder)}`)}</section>
  <div class="ctf-reset"><button class="ghost" data-action="ctf-reset-request">↻ Recommencer le module</button>${ctfResetPending?`<div class="ctf-reset-confirm" role="group" aria-label="Confirmer la remise à zéro"><p>Effacer les flags validés et les indices affichés du Module ${escapeHtml(mod.id)} ? L’archive dans ta VM ne sera pas modifiée.</p><button class="secondary" data-action="ctf-reset-confirm">Oui, recommencer</button><button class="ghost" data-action="ctf-reset-cancel">Annuler</button></div>`:''}</div>
  ${done.length===mod.challenges.length?'<div class="ctf-complete" role="status">✓ Module terminé ! Tu peux rejouer chaque défi et expliquer comment tu as écarté les leurres.</div>':''}
  <div class="ctf-layout"><nav class="ctf-map" aria-label="Défis du module"><div class="ctf-map-title">LES DÉFIS <span>${done.length}/${mod.challenges.length}</span></div>${mod.challenges.map((challenge,i)=>`<button class="ctf-map-item ${i===index?'active':''} ${done.includes(challenge.id)?'done':''}" data-ctf-step="${i}" aria-current="${i===index?'step':'false'}"><span class="ctf-map-number">${String(i+1).padStart(2,'0')}</span><span>${escapeHtml(challenge.title)}</span><span class="ctf-map-check">${done.includes(challenge.id)?'✓':'→'}</span></button>`).join('')}</nav>
  <section class="panel ctf-challenge"><div class="ctf-challenge-meta"><span>DÉFI ${String(index+1).padStart(2,'0')} / ${mod.challenges.length}</span><span>${escapeHtml(current.command)}</span></div><h2>${escapeHtml(current.title)}</h2><p class="ctf-story">${escapeHtml(current.story)}</p><div class="ctf-question"><span>TA MISSION</span><p>${escapeHtml(current.question)}</p></div>
  ${solved?`<div class="ctf-solved"><strong>✓ Flag trouvé</strong><p>${escapeHtml(current.success)}</p></div>`:`<form id="ctf-form" class="ctf-form"><label for="ctf-flag">Flag découvert dans la VM</label><div><input id="ctf-flag" name="flag" placeholder="FLAG{...}" autocomplete="off" autocapitalize="off" spellcheck="false" required><button class="primary" type="submit">Valider le flag →</button></div><p class="feedback ${ctfFeedback?'error':''}" role="status">${escapeHtml(ctfFeedback)}</p></form>`}
  <div class="ctf-hints"><button class="ghost" data-action="ctf-hint" ${hintsShown>=current.hints.length?'disabled':''}>${hintsShown>=current.hints.length?'Tous les indices affichés':'Voir un indice'}</button>${current.hints.slice(0,hintsShown).map((hint,i)=>`<div class="hint-box"><div class="hint-label">INDICE ${i+1}</div>${escapeHtml(hint)}</div>`).join('')}</div>
  <div class="next-row"><button class="ghost" data-ctf-step="${Math.max(0,index-1)}" ${index===0?'disabled':''}>← Défi précédent</button><button class="secondary" data-ctf-step="${Math.min(mod.challenges.length-1,index+1)}" ${index===mod.challenges.length-1?'disabled':''}>Défi suivant →</button></div></section></div>`;
}

function renderMission(m){
  const n=missions.findIndex(x=>x.id===m.id);
  const mod=missionModule(m.id);
  return `<div class="breadcrumbs"><button data-route="accueil">Accueil</button><span>›</span><span>Étape ${mod.id}</span><span>›</span><span>Mission ${m.id}</span></div>
  <div class="mission-header"><div><p class="eyebrow">MISSION ${m.id} · ${m.time.toUpperCase()} · ÉTAPE ${mod.id}</p><h1 class="page-title">${m.title}</h1><p class="mission-subtitle">${m.subtitle}</p></div><span class="mission-badge ${state.done.includes(m.id)?'done':''}">${state.done.includes(m.id)?'✓ VALIDÉE':'À RÉALISER'}</span></div>
  <div class="mission-layout"><div><section class="panel"><h2>La situation</h2><p>${m.scenario}</p><div class="callout">Travaille depuis la racine du dossier <code>atelier-linux</code> dans ta VM. Besoin de le retrouver ? Lance <code>pwd</code> et <code>ls</code>.</div><h2>À toi de jouer</h2><ol class="task-list">${m.steps.map(x=>`<li>${x}</li>`).join('')}</ol>${m.note?`<p class="small-note">${m.note}</p>`:''}</section>
  <section class="panel"><h2>Un coup de pouce ?</h2><p>Essaie d’abord par toi-même. Dévoile un indice à la fois si tu bloques.</p><div id="hints">${m.hints.slice(0,revealed).map((h,i)=>`<div class="hint-box"><div class="hint-label">INDICE ${i+1}</div>${h}</div>`).join('')}${revealed>m.hints.length?`<div class="hint-box"><div class="hint-label">EXEMPLE DE SOLUTION</div><pre>${escapeHtml(m.solution)}</pre></div>`:''}</div><div class="reveal-row">${revealed<=m.hints.length?`<button class="ghost" data-action="hint">${revealed<m.hints.length?'Voir l’indice '+(revealed+1):'Voir un exemple de solution'}</button>`:''}</div></section>
  <section class="verification"><h2>Vérifie dans ta VM</h2><p>Le vérificateur lit le résultat de ton travail. Il affiche un code seulement si la mission est réussie.</p><div class="code-row"><div class="code-inline">bash verifier.sh ${m.id}</div><button class="copy-btn" data-copy="bash verifier.sh ${m.id}" aria-label="Copier la commande de vérification">Copier</button></div><form class="verify-form" id="verify-form"><input name="token" aria-label="Code de validation affiché dans la VM" placeholder="CODE AFFICHÉ PAR LA VM" autocomplete="off" required><button class="primary" type="submit">Valider →</button></form><p id="verify-feedback" class="feedback ${feedback?'error':''}" role="status">${feedback}</p></section>
  <div class="next-row"><button class="ghost" data-route="${n>0?'mission-'+missions[n-1].id:'accueil'}">← ${n>0?'Mission précédente':'Accueil'}</button><button class="secondary" data-route="${n<missions.length-1?'mission-'+missions[n+1].id:'revision'}">${n<missions.length-1?'Mission suivante':'Réviser'} →</button></div></div>
  <aside class="mission-aside"><div class="side-card"><h3>Commandes utiles</h3><div class="tag-list">${m.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div></div><div class="side-card"><h3>À retenir</h3><p class="tip">${m.tip}</p></div><div class="side-card"><h3>Besoin de l’archive ?</h3><p><a href="${archiveUrl}">Télécharger les fichiers d’exercice depuis GitHub ↓</a><br>Dans la VM : <code>tar -xzf atelier-linux.tar.gz</code>, puis <code>cd atelier-linux</code>.</p></div></aside></div>`;
}

function renderGuide(){return `<div class="breadcrumbs"><button data-route="accueil">Accueil</button><span>›</span><span>Guide de survie</span></div><p class="eyebrow">À GARDER SOUS LA MAIN</p><h1 class="page-title">Guide de survie</h1><p class="page-intro">Une antisèche pour t’aider pendant les missions et au travail. L’objectif est de savoir retrouver une commande et de vérifier son effet, pas de tout apprendre par cœur.</p>
  <div class="guide-grid"><section class="panel"><h2>Se déplacer</h2><dl><dt>pwd</dt><dd>Affiche le dossier courant.</dd><dt>ls</dt><dd>Affiche les fichiers et dossiers visibles.</dd><dt>cd dossier</dt><dd>Entre dans un dossier.</dd><dt>cd dossier/dossier2</dt><dd>Entre directement dans un sous-dossier.</dd><dt>cd ..</dt><dd>Revient dans le répertoire parent.</dd><dt>cd ~</dt><dd>Retourne dans le dossier personnel.</dd></dl></section>
  <section class="panel"><h2>Fichiers et dossiers</h2><dl><dt>mkdir d</dt><dd>Crée un dossier.</dd><dt>touch f</dt><dd>Crée un fichier vide.</dd><dt>cp a b</dt><dd>Copie a vers b.</dd><dt>mv a b</dt><dd>Déplace ou renomme a en b.</dd><dt>rm f</dt><dd>Supprime un fichier. Vérifie la cible avant.</dd></dl></section>
  <section class="panel"><h2>Texte et flux</h2><dl><dt>cat f</dt><dd>Affiche le contenu d’un fichier.</dd><dt>less f</dt><dd>Parcourt un fichier ; touche q pour quitter.</dd><dt>grep mot f</dt><dd>Affiche les lignes du fichier f contenant mot.</dd><dt>cmd &gt; f</dt><dd>Écrit la sortie dans f en remplaçant son contenu.</dd><dt>cmd &gt;&gt; f</dt><dd>Ajoute la sortie à la fin de f.</dd><dt>a | b</dt><dd>Envoie la sortie de a à l’entrée de b.</dd></dl></section>
  <section class="panel"><h2>Découper et compter</h2><dl><dt>cut</dt><dd>Extrait des colonnes.</dd><dt>sort</dt><dd>Trie les lignes.</dd><dt>uniq</dt><dd>Retire les lignes identiques voisines.</dd><dt>wc -l</dt><dd>Compte les lignes.</dd><dt>find</dt><dd>Recherche dans les dossiers.</dd></dl></section>
  <section class="panel"><h2>Système</h2><dl><dt>ls -la</dt><dd>Affiche aussi les noms commençant par « . », cachés par défaut.</dd><dt>ls -l</dt><dd>Montre les droits d’accès.</dd><dt>chmod u+x</dt><dd>Ajoute l’exécution au propriétaire.</dd><dt>tar -czf</dt><dd>Crée une archive compressée.</dd><dt>tar -tzf</dt><dd>Liste le contenu de l’archive.</dd><dt>tar -xzf</dt><dd>Extrait une archive gzip.</dd><dt>Ctrl-C</dt><dd>Interrompt un programme au premier plan.</dd><dt>Ctrl-Z</dt><dd>Suspend le programme au premier plan.</dd><dt>bg</dt><dd>Reprend un job suspendu en arrière-plan.</dd><dt>fg</dt><dd>Ramène un job au premier plan.</dd></dl></section>
  <section class="panel"><h2>Rechercher de l’aide</h2><dl><dt>man ls</dt><dd>Ouvre le manuel de ls ; q pour quitter.</dd><dt>commande --help</dt><dd>Affiche souvent une aide courte.</dd><dt>Tab</dt><dd>Complète un nom de fichier ou de commande.</dd><dt>↑ / ↓</dt><dd>Parcourt les commandes déjà saisies.</dd><dt>Ctrl-R</dt><dd>Recherche dans l’historique du shell.</dd></dl></section>
  <section class="panel"><h2>Stockage et intégrité</h2><dl><dt>du -sh d</dt><dd>Taille occupée par un dossier.</dd><dt>df -h</dt><dd>Place libre des systèmes de fichiers.</dd><dt>sha256sum</dt><dd>Calcule une empreinte de fichier.</dd><dt>stat</dt><dd>Affiche métadonnées et droits précis.</dd></dl></section>
  <section class="panel"><h2>Diagnostic</h2><dl><dt>tail -n 20</dt><dd>Dernières lignes d’un fichier.</dd><dt>grep -n -C 2</dt><dd>Résultats avec numéros et contexte.</dd><dt>sed</dt><dd>Transforme du texte.</dd><dt>awk</dt><dd>Traite colonnes et regroupements.</dd><dt>ps / kill</dt><dd>Observe un processus et lui envoie un signal.</dd></dl></section>
  <section class="panel"><h2>AlmaLinux</h2><dl><dt>rpm -q</dt><dd>Interroge les paquets installés.</dd><dt>dnf repolist</dt><dd>Affiche les dépôts configurés.</dd><dt>systemctl</dt><dd>Observe les unités et services.</dd><dt>journalctl</dt><dd>Consulte le journal système.</dd><dt>ip / ss</dt><dd>Inspecte interfaces et sockets.</dd><dt>getenforce</dt><dd>Affiche le mode SELinux.</dd></dl></section></div>
  <div class="alert" style="margin-top:22px">Attention : <code>rm</code> et <code>></code> peuvent supprimer un résultat existant. Avant d’appuyer sur Entrée, vérifie le dossier courant, les chemins et les jokers.</div><p style="margin-top:20px"><button class="secondary" data-view="cours">Ouvrir les fiches de cours →</button></p>`}

function renderCourseList(query=''){
  const search=query.trim().toLocaleLowerCase('fr');
  const found=lessons.filter(l=>`${l.label} ${l.group} ${l.summary}`.toLocaleLowerCase('fr').includes(search));
  if(!found.length)return '<p class="course-empty">Aucune fiche trouvée. Essaie un nom de commande ou un sujet plus court.</p>';
  return [...new Set(found.map(l=>l.group))].map(group=>`<section class="course-group"><h2>${group}</h2><div class="course-grid">${found.filter(l=>l.group===group).map(l=>`<button class="course-card" data-route="fiche-${l.id}"><span class="course-command">${escapeHtml(l.label)}</span><span>${escapeHtml(l.summary)}</span><span class="course-arrow">Lire la fiche →</span></button>`).join('')}</div></section>`).join('');
}

function renderCourse(){return `<div class="breadcrumbs"><button data-route="accueil">Accueil</button><span>›</span><span>Cours express</span></div><p class="eyebrow">UNE COMMANDE À LA FOIS</p><h1 class="page-title">Cours express</h1><p class="page-intro">${lessons.length} fiches pour comprendre les commandes utiles, leurs options et leurs pièges. Chaque fiche propose des exemples et un entraînement ; le manuel <code>man</code> reste la référence complète.</p><label class="course-search-label" for="course-search">Rechercher une commande ou un thème</label><input id="course-search" class="course-search" type="search" placeholder="Ex. chmod, journaux, dossiers…" autocomplete="off"><div id="course-list">${renderCourseList()}</div>`}

function renderLesson(id){
  const l=lessons.find(item=>item.id===id);
  if(!l)return renderCourse();
  return `<div class="breadcrumbs"><button data-route="accueil">Accueil</button><span>›</span><button data-view="cours">Cours express</button><span>›</span><span>${escapeHtml(l.label)}</span></div><p class="eyebrow">FICHE DE COURS · ${escapeHtml(l.group).toUpperCase()}</p><h1 class="page-title">${escapeHtml(l.label)}</h1><p class="page-intro">${escapeHtml(l.summary)}</p><article class="panel lesson-article">${l.html}</article><div class="next-row"><button class="ghost" data-view="cours">← Toutes les fiches</button>${l.mission?`<button class="secondary" data-route="mission-${l.mission}">Pratiquer · mission ${l.mission} →</button>`:''}</div>`;
}

function startQuiz(mode='due'){
  quizMode=mode;
  quizSession=mode==='practice'?unlockedCards():mode==='missed'?missedCards():dueCards();
  quizIndex=0;
  quizAnswer=null;
  render();
}
function quizActions(){
  return `${dueCards().length?'<button class="secondary" data-action="restart-quiz">Revoir les cartes à travailler →</button>':''}${missedCards().length?`<button class="ghost" data-action="missed-quiz">Revoir mes erreurs (${missedCards().length}) ↻</button>`:''}${unlockedCards().length?'<button class="ghost" data-action="practice-quiz">Revoir toutes mes cartes ↻</button>':''}`;
}
function renderQuiz(){
  if(!quizSession.length && quizIndex===0) quizSession=quizMode==='practice'?unlockedCards():quizMode==='missed'?missedCards():dueCards();
  const card=quizSession[quizIndex];
  const header='<div class="breadcrumbs"><button data-route="accueil">Accueil</button><span>›</span><span>Révisions</span></div>';
  if(!card) return `${header}<p class="eyebrow">MÉMORISATION</p><h1 class="page-title">Révisions</h1><div class="empty-state"><h2>${quizMode!=='due'?'Entraînement terminé !':dueCards().length?'Session terminée !':state.done.length?'Tout est à jour.':'Les cartes arrivent après les missions.'}</h2><p>${unlockedCards().length?'Tu peux refaire toutes les cartes débloquées ou seulement tes erreurs. L’entraînement libre ne change pas leur date de rappel.':'Valide ta première mission dans la VM pour débloquer les premières questions de rappel.'}</p><div class="quiz-actions">${quizActions()||'<button class="ghost" data-route="accueil">Voir les missions →</button>'}</div></div>`;
  const intro=quizMode==='due'?'Réponds de mémoire. Une erreur reviendra à la prochaine séance ; les bonnes réponses s’espacent progressivement.':quizMode==='missed'?'Revois uniquement les cartes auxquelles tu t’es trompé. Une bonne réponse retire la carte de cette liste.':'Tu peux refaire toutes les cartes débloquées. Les réponses ici ne modifient pas tes prochains rappels.';
  return `${header}<p class="eyebrow">${quizMode==='due'?'RAPPEL ACTIF · 2 MINUTES':quizMode==='missed'?'MES ERREURS':'ENTRAÎNEMENT LIBRE'}</p><h1 class="page-title">Qu’as-tu retenu ?</h1><p class="page-intro">${intro}</p><div class="quiz-toolbar">${quizActions()}</div><section class="panel quiz-card"><div class="quiz-meta"><span>CARTE ${quizIndex+1} / ${quizSession.length}</span><span>${quizMode==='due'?dueCards().length+' À REVOIR':quizMode==='missed'?'MES ERREURS':'MODE LIBRE'}</span></div><h2>${card.question}</h2><div class="quiz-options">${card.options.map((o,i)=>`<button class="quiz-option ${quizAnswer!==null?(i===card.answer?'correct':i===quizAnswer?'incorrect':''):''}" data-answer="${i}" ${quizAnswer!==null?'disabled':''}>${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>${quizAnswer!==null?`<div class="quiz-explain">${quizAnswer===card.answer?'Exact.':'Pas encore.'} ${card.explain}</div><button class="primary" data-action="next-card">${quizIndex===quizSession.length-1?'Terminer':'Carte suivante'} →</button>`:''}</section>`;
}

function answerQuiz(index){
  if(quizAnswer!==null)return;
  const card=quizSession[quizIndex];
  if(!card)return;
  quizAnswer=index;
  const previous=state.cards[card.id]||{level:0};
  const wrong=index!==card.answer;
  if(quizMode==='due'){
    if(wrong)state.cards[card.id]={level:0,due:today(),wrong:true};
    else{const level=Math.min(previous.level+1,4);state.cards[card.id]={level,due:later([0,1,3,7,14][level]),wrong:false}}
  }else state.cards[card.id]={...previous,due:previous.due || today(),wrong};
  persist();
  render();
}

function render(){
  const route=getRoute();renderNav();applySidebarState();
  const view=document.getElementById('view');
  if(route==='accueil')view.innerHTML=renderHome();
  else if(route.startsWith('module-')){const mod=ctfModules.find(m=>route==='module-'+m.id);view.innerHTML=mod?renderCtfModule(mod):renderHome()}
  else if(route==='guide')view.innerHTML=renderGuide();
  else if(route==='cours')view.innerHTML=renderCourse();
  else if(route.startsWith('fiche-'))view.innerHTML=renderLesson(route.slice(6));
  else if(route==='revision')view.innerHTML=renderQuiz();
  else if(route.startsWith('mission-')){const m=missions.find(x=>x.id===route.slice(8));view.innerHTML=m?renderMission(m):renderHome()}
  else view.innerHTML=renderHome();
  document.title=`${route==='accueil'?'Parcours Linux':route.startsWith('module-')?ctfModules.find(m=>route==='module-'+m.id)?.title||'Module CTF':route==='guide'?'Guide de survie':route==='cours'?'Cours express':route.startsWith('fiche-')?lessons.find(l=>route==='fiche-'+l.id)?.label||'Cours express':route==='revision'?'Révisions':missions.find(m=>route==='mission-'+m.id)?.title||'Parcours Linux'} — Linux, pour de vrai`;
}

document.addEventListener('click',async e=>{
  const nav=e.target.closest('[data-route],[data-view]');if(nav){const dest=nav.dataset.route||nav.dataset.view;revealed=0;feedback='';ctfFeedback='';ctfResetPending=false;if(dest==='revision'){quizMode='due';quizSession=[];quizIndex=0;quizAnswer=null}routeTo(dest);window.scrollTo({top:0,behavior:'smooth'});return}
  const ctfStep=e.target.closest('[data-ctf-step]');if(ctfStep){const mod=ctfModules.find(m=>getRoute()==='module-'+m.id);if(mod)ctfActive[mod.id]=Number(ctfStep.dataset.ctfStep);ctfFeedback='';ctfResetPending=false;render();return}
  const action=e.target.closest('[data-action]');if(action){const mod=ctfModules.find(m=>getRoute()==='module-'+m.id);if(action.dataset.action==='toggle-sidebar'){state.sidebarHidden=!state.sidebarHidden;persist();applySidebarState()}if(action.dataset.action==='setup'){document.getElementById('installation')?.scrollIntoView({behavior:'smooth'})}if(action.dataset.action==='hint'){revealed++;render()}if(action.dataset.action==='ctf-hint'&&mod){const challenge=ctfCurrent(mod);const key=`${mod.id}-${challenge.id}`;ctfHints[key]=Math.min((ctfHints[key]||0)+1,challenge.hints.length);render()}if(action.dataset.action==='ctf-reset-request'&&mod){ctfResetPending=true;render()}if(action.dataset.action==='ctf-reset-cancel'){ctfResetPending=false;render()}if(action.dataset.action==='ctf-reset-confirm'&&mod&&ctfResetPending){resetCtfModule(mod);render()}if(action.dataset.action==='next-card'){quizIndex++;quizAnswer=null;render()}if(action.dataset.action==='restart-quiz'){if(dueCards().length)startQuiz();else routeTo('accueil')}if(action.dataset.action==='practice-quiz')startQuiz('practice');if(action.dataset.action==='missed-quiz')startQuiz('missed');return}
  const answer=e.target.closest('[data-answer]');if(answer){answerQuiz(Number(answer.dataset.answer));return}
  const copy=e.target.closest('[data-copy]');if(copy){try{await navigator.clipboard.writeText(copy.dataset.copy);copy.textContent='Copié ✓'}catch{copy.textContent='Sélectionne la commande'}return}
});

document.addEventListener('submit',e=>{
  if(e.target.id==='ctf-form'){
    e.preventDefault();
    const mod=ctfModules.find(m=>getRoute()==='module-'+m.id);
    if(!mod)return;
    const challenge=ctfCurrent(mod);
    const result=validateCtfFlag(mod,challenge,new FormData(e.target).get('flag').toString());
    if(result.valid){ctfFeedback='';render()}
    else{
      ctfFeedback=result.message;
      const target=e.target.querySelector('.feedback');target.textContent=ctfFeedback;target.className='feedback error';
    }
    return;
  }
  if(e.target.id!=='verify-form')return;e.preventDefault();const m=missions.find(x=>getRoute()==='mission-'+x.id);if(!m)return;const value=new FormData(e.target).get('token').toString().trim().toUpperCase();const target=document.getElementById('verify-feedback');if(value===m.token){if(!state.done.includes(m.id))state.done.push(m.id);persist();target.textContent='Mission validée. Bien joué !';target.className='feedback success';renderNav();document.querySelector('.mission-badge').textContent='✓ VALIDÉE';document.querySelector('.mission-badge').classList.add('done')}else{target.textContent='Ce code ne correspond pas. Lance la commande de vérification dans ta VM et reporte le code affiché après « VALIDÉ ».';target.className='feedback error'}
});
document.addEventListener('change',e=>{if(e.target.id==='mission-select'&&e.target.value){routeTo(e.target.value);window.scrollTo(0,0)}});
document.addEventListener('input',e=>{if(e.target.id==='course-search'){document.getElementById('course-list').innerHTML=renderCourseList(e.target.value)}});
window.addEventListener('hashchange',()=>{revealed=0;feedback='';ctfFeedback='';ctfResetPending=false;render();window.scrollTo(0,0)});
render();
